# Generated by Django 3.0.8 on 2020-08-21 14:17

import cards.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=45)),
                ('character', models.CharField(max_length=45)),
                ('pinyin', models.CharField(max_length=45)),
                ('comment', models.CharField(max_length=255)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('due', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=models.SET(cards.models.get_sentinel_user), related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
