# Generated by Django 3.0.8 on 2020-08-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_cardsondeck_deck'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cardsondeck',
            constraint=models.UniqueConstraint(fields=('card', 'deck'), name='unique_cards_on_deck'),
        ),
        migrations.AddConstraint(
            model_name='deck',
            constraint=models.UniqueConstraint(condition=models.Q(name='All Cards'), fields=('created_by',), name='user_all_cards'),
        ),
    ]
