# Generated by Django 3.0.8 on 2020-08-31 09:34

import cards.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20200831_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(cards.models.get_sentinel_user), related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
